name: Create Readme & Project Files 

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-2019
    steps:
      # main ブランチをチェックアウトする
      - name: checkout main
        uses: actions/checkout@v2
        with:
          ref: main
      # Readmeを作成する
      - name: Create Readme
        env:
          REVIEWERS: "rito328"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.create_branch.outputs.branch_name }}
        run: |
          git pull origin "main"
          powershell -NoProfile -ExecutionPolicy Unrestricted .\down.ps1
            git config --global user.email "actions@example.com"
            git config --global user.name "Create Readme & Project Files" 
          git add .
          git commit -m "ページ自動更新"
          git push origin "main"
